import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:riverpod/riverpod.dart';
import '../models/notification.dart';
import '../models/user.dart';

final notificationServiceProvider = Provider<NotificationService>((ref) {
  return NotificationService();
});

class NotificationService {
  final SupabaseClient _supabase = Supabase.instance.client;

  // Notification CRUD Operations
  Future<AppNotification?> createNotification(AppNotification notification) async {
    try {
      final response = await _supabase
          .from('notifications')
          .insert(notification.toJson())
          .select()
          .single();

      return AppNotification.fromJson(response);
    } catch (e) {
      debugPrint('Error creating notification: $e');
      return null;
    }
  }

  Future<List<AppNotification>> getNotificationsByUser(String userId) async {
    try {
      final response = await _supabase
          .from('notifications')
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      return (response as List)
          .map((json) => AppNotification.fromJson(json))
          .toList();
    } catch (e) {
      debugPrint('Error getting notifications by user: $e');
      return [];
    }
  }

  Future<List<AppNotification>> getUnreadNotificationsByUser(String userId) async {
    try {
      final response = await _supabase
          .from('notifications')
          .select()
          .eq('user_id', userId)
          .eq('is_read', false)
          .order('created_at', ascending: false);

      return (response as List)
          .map((json) => AppNotification.fromJson(json))
          .toList();
    } catch (e) {
      debugPrint('Error getting unread notifications: $e');
      return [];
    }
  }

  Future<bool> markNotificationAsRead(String notificationId) async {
    try {
      await _supabase
          .from('notifications')
          .update({'is_read': true})
          .eq('id', notificationId);

      return true;
    } catch (e) {
      debugPrint('Error marking notification as read: $e');
      return false;
    }
  }

  Future<bool> markAllNotificationsAsRead(String userId) async {
    try {
      await _supabase
          .from('notifications')
          .update({'is_read': true})
          .eq('user_id', userId)
          .eq('is_read', false);

      return true;
    } catch (e) {
      debugPrint('Error marking all notifications as read: $e');
      return false;
    }
  }

  Future<bool> deleteNotification(String notificationId) async {
    try {
      await _supabase
          .from('notifications')
          .delete()
          .eq('id', notificationId);

      return true;
    } catch (e) {
      debugPrint('Error deleting notification: $e');
      return false;
    }
  }

  // Admin Notification Operations
  Future<bool> sendBroadcastNotification({
    required String title,
    required String message,
    NotificationType type = NotificationType.info,
    Map<String, dynamic> data = const {},
  }) async {
    try {
      // Get all users
      final usersResponse = await _supabase
          .from('users')
          .select('id');

      final users = usersResponse as List;
      
      // Create notifications for all users
      final notifications = users.map((user) {
        return {
          'id': '', // Will be generated by database
          'user_id': user['id'],
          'title': title,
          'message': message,
          'type': type.value,
          'is_read': false,
          'data': data,
          'created_at': DateTime.now().toIso8601String(),
        };
      }).toList();

      await _supabase
          .from('notifications')
          .insert(notifications);

      return true;
    } catch (e) {
      debugPrint('Error sending broadcast notification: $e');
      return false;
    }
  }

  Future<bool> sendTargetedNotification({
    required List<String> userIds,
    required String title,
    required String message,
    NotificationType type = NotificationType.info,
    Map<String, dynamic> data = const {},
  }) async {
    try {
      // Create notifications for specific users
      final notifications = userIds.map((userId) {
        return {
          'id': '', // Will be generated by database
          'user_id': userId,
          'title': title,
          'message': message,
          'type': type.value,
          'is_read': false,
          'data': data,
          'created_at': DateTime.now().toIso8601String(),
        };
      }).toList();

      await _supabase
          .from('notifications')
          .insert(notifications);

      return true;
    } catch (e) {
      debugPrint('Error sending targeted notification: $e');
      return false;
    }
  }

  Future<bool> sendRoleBasedNotification({
    required UserRole role,
    required String title,
    required String message,
    NotificationType type = NotificationType.info,
    Map<String, dynamic> data = const {},
  }) async {
    try {
      // Get users by role
      final usersResponse = await _supabase
          .from('users')
          .select('id')
          .eq('role', role.value);

      final users = usersResponse as List;
      
      // Create notifications for users with specified role
      final notifications = users.map((user) {
        return {
          'id': '', // Will be generated by database
          'user_id': user['id'],
          'title': title,
          'message': message,
          'type': type.value,
          'is_read': false,
          'data': data,
          'created_at': DateTime.now().toIso8601String(),
        };
      }).toList();

      await _supabase
          .from('notifications')
          .insert(notifications);

      return true;
    } catch (e) {
      debugPrint('Error sending role-based notification: $e');
      return false;
    }
  }

  // Notification Statistics
  Future<Map<String, dynamic>> getNotificationStatistics() async {
    try {
      // Get total notifications
      final totalResponse = await _supabase
          .from('notifications')
          .select('id');

      // Get unread notifications
      final unreadResponse = await _supabase
          .from('notifications')
          .select('id')
          .eq('is_read', false);

      // Get notifications by type
      final typeResponse = await _supabase
          .from('notifications')
          .select('type');

      final total = totalResponse as List;
      final unread = unreadResponse as List;
      final types = typeResponse as List;

      // Calculate type breakdown
      final typeCounts = <String, int>{};
      for (final notification in types) {
        final type = notification['type'] as String;
        typeCounts[type] = (typeCounts[type] ?? 0) + 1;
      }

      return {
        'totalNotifications': total.length,
        'unreadNotifications': unread.length,
        'readNotifications': total.length - unread.length,
        'typeBreakdown': typeCounts,
      };
    } catch (e) {
      debugPrint('Error getting notification statistics: $e');
      return {};
    }
  }

  Future<Map<String, dynamic>> getUserNotificationStatistics(String userId) async {
    try {
      // Get user's notifications
      final userResponse = await _supabase
          .from('notifications')
          .select('is_read, type')
          .eq('user_id', userId);

      final notifications = userResponse as List;
      
      // Calculate statistics
      int unreadCount = 0;
      final typeCounts = <String, int>{};

      for (final notification in notifications) {
        final isRead = notification['is_read'] as bool;
        final type = notification['type'] as String;

        if (!isRead) unreadCount++;
        typeCounts[type] = (typeCounts[type] ?? 0) + 1;
      }

      return {
        'totalNotifications': notifications.length,
        'unreadNotifications': unreadCount,
        'readNotifications': notifications.length - unreadCount,
        'typeBreakdown': typeCounts,
      };
    } catch (e) {
      debugPrint('Error getting user notification statistics: $e');
      return {};
    }
  }

  // Real-time updates preparation
  Stream<List<AppNotification>> watchUserNotifications(String userId) {
    return _supabase
        .from('notifications')
        .stream(primaryKey: ['id'])
        .order('created_at', ascending: false)
        .map((rows) => rows
            .where((r) => r['user_id'] == userId)
            .map((json) => AppNotification.fromJson(json))
            .toList());
  }

  Stream<int> watchUnreadCount(String userId) {
    return _supabase
        .from('notifications')
        .stream(primaryKey: ['id'])
        .map((rows) => rows
            .where((r) => r['user_id'] == userId && r['is_read'] == false)
            .length);
  }

  // Notification templates for common events
  Future<bool> sendEventUpdateNotification({
    required String eventId,
    required String eventTitle,
    required String updateType,
    List<String>? targetedUserIds,
  }) async {
    String title;
    String message;
    NotificationType type;

    switch (updateType) {
      case 'activated':
        title = 'Event Started!';
        message = 'The event "$eventTitle" has started. Voting is now open!';
        type = NotificationType.eventUpdate;
        break;
      case 'completed':
        title = 'Event Completed';
        message = 'The event "$eventTitle" has ended. Check out the results!';
        type = NotificationType.eventUpdate;
        break;
      case 'cancelled':
        title = 'Event Cancelled';
        message = 'The event "$eventTitle" has been cancelled.';
        type = NotificationType.info;
        break;
      default:
        title = 'Event Update';
        message = 'There\'s an update for the event "$eventTitle".';
        type = NotificationType.eventUpdate;
    }

    if (targetedUserIds != null) {
      return sendTargetedNotification(
        userIds: targetedUserIds,
        title: title,
        message: message,
        type: type,
        data: {'event_id': eventId, 'update_type': updateType},
      );
    } else {
      return sendBroadcastNotification(
        title: title,
        message: message,
        type: type,
        data: {'event_id': eventId, 'update_type': updateType},
      );
    }
  }

  Future<bool> sendVoteReminderNotification({
    required String eventId,
    required String eventTitle,
    List<String>? targetedUserIds,
  }) async {
    const title = 'Vote Now!';
    final message = 'Don\'t forget to vote in the event "$eventTitle". Your voice matters!';

    if (targetedUserIds != null) {
      return sendTargetedNotification(
        userIds: targetedUserIds,
        title: title,
        message: message,
        type: NotificationType.voteReminder,
        data: {'event_id': eventId},
      );
    } else {
      return sendBroadcastNotification(
        title: title,
        message: message,
        type: NotificationType.voteReminder,
        data: {'event_id': eventId},
      );
    }
  }

  Future<bool> sendPerformerApprovalNotification({
    required String performerId,
    required String performerName,
    required bool isApproved,
  }) async {
    final title = isApproved ? 'Profile Approved!' : 'Profile Rejected';
    final message = isApproved 
        ? 'Your performer profile has been approved. You can now participate in events!'
        : 'Your performer profile has been rejected. Please review the guidelines and try again.';
    final type = isApproved ? NotificationType.success : NotificationType.error;

    return sendTargetedNotification(
      userIds: [performerId],
      title: title,
      message: message,
      type: type,
      data: {'performer_id': performerId, 'approval_status': isApproved ? 'approved' : 'rejected'},
    );
  }
}
